spring.application.name=ems

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management
spring.datasource.username=postgres
spring.datasource.password=HAF4268IZH

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=development-secret-key-yang-cukup-panjang
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000
